
source = src/Daisy.cs \
	src/AST.cs \
	src/Builder.cs \
	src/IL.cs \
	bin/Parser.cs \
	bin/Scanner.cs \
	cecil/Mono/Empty.cs \
	cecil/Mono/Actions.cs \
	cecil/Mono/Funcs.cs \
	cecil/Mono.Cecil.Cil/OpCode.cs \
	cecil/Mono.Cecil.Cil/Code.cs \
	cecil/Mono.Cecil.Cil/Instruction.cs \
	cecil/Mono.Cecil.Cil/SequencePoint.cs \
	cecil/Mono.Cecil.Cil/VariableReference.cs \
	cecil/Mono.Cecil.Cil/ExceptionHandler.cs \
	cecil/Mono.Cecil.Cil/OpCodes.cs \
	cecil/Mono.Cecil.Cil/VariableDefinition.cs \
	cecil/Mono.Cecil.Cil/Document.cs \
	cecil/Mono.Cecil.Cil/MethodBody.cs \
	cecil/Mono.Cecil.Cil/ILProcessor.cs \
	cecil/Mono.Cecil.Cil/CodeReader.cs \
	cecil/Mono.Cecil.Cil/Symbols.cs \
	cecil/Mono.Cecil.Cil/CodeWriter.cs \
	cecil/Mono.Security.Cryptography/CryptoService.cs \
	cecil/Mono.Security.Cryptography/CryptoConvert.cs \
	cecil/Mono.Cecil.PE/ByteBuffer.cs \
	cecil/Mono.Cecil.PE/ByteBufferEqualityComparer.cs \
	cecil/Mono.Cecil.PE/ImageReader.cs \
	cecil/Mono.Cecil.PE/ImageWriter.cs \
	cecil/Mono.Cecil.PE/BinaryStreamWriter.cs \
	cecil/Mono.Cecil.PE/Section.cs \
	cecil/Mono.Cecil.PE/BinaryStreamReader.cs \
	cecil/Mono.Cecil.PE/TextMap.cs \
	cecil/Mono.Cecil.PE/Image.cs \
	cecil/Mono.Cecil.PE/DataDirectory.cs \
	cecil/Mono.Collections.Generic/Collection.cs \
	cecil/Mono.Collections.Generic/ReadOnlyCollection.cs \
	cecil/Mono.Cecil.Metadata/CodedIndex.cs \
	cecil/Mono.Cecil.Metadata/ElementType.cs \
	cecil/Mono.Cecil.Metadata/Heap.cs \
	cecil/Mono.Cecil.Metadata/Utilities.cs \
	cecil/Mono.Cecil.Metadata/UserStringHeap.cs \
	cecil/Mono.Cecil.Metadata/GuidHeap.cs \
	cecil/Mono.Cecil.Metadata/MetadataToken.cs \
	cecil/Mono.Cecil.Metadata/Row.cs \
	cecil/Mono.Cecil.Metadata/TableHeap.cs \
	cecil/Mono.Cecil.Metadata/TokenType.cs \
	cecil/Mono.Cecil.Metadata/Buffers.cs \
	cecil/Mono.Cecil.Metadata/StringHeap.cs \
	cecil/Mono.Cecil.Metadata/BlobHeap.cs \
	cecil/Mono.Cecil/TypeSpecification.cs \
	cecil/Mono.Cecil/ICustomAttributeProvider.cs \
	cecil/Mono.Cecil/NativeType.cs \
	cecil/Mono.Cecil/MethodSpecification.cs \
	cecil/Mono.Cecil/TypeSystem.cs \
	cecil/Mono.Cecil/AssemblyDefinition.cs \
	cecil/Mono.Cecil/MetadataResolver.cs \
	cecil/Mono.Cecil/IMetadataTokenProvider.cs \
	cecil/Mono.Cecil/Modifiers.cs \
	cecil/Mono.Cecil/MethodReference.cs \
	cecil/Mono.Cecil/IMetadataScope.cs \
	cecil/Mono.Cecil/MethodImplAttributes.cs \
	cecil/Mono.Cecil/DefaultAssemblyResolver.cs \
	cecil/Mono.Cecil/PInvokeAttributes.cs \
	cecil/Mono.Cecil/TypeParser.cs \
	cecil/Mono.Cecil/MethodCallingConvention.cs \
	cecil/Mono.Cecil/MarshalInfo.cs \
	cecil/Mono.Cecil/IConstantProvider.cs \
	cecil/Mono.Cecil/CustomAttribute.cs \
	cecil/Mono.Cecil/MethodAttributes.cs \
	cecil/Mono.Cecil/FieldDefinition.cs \
	cecil/Mono.Cecil/CallSite.cs \
	cecil/Mono.Cecil/ModuleKind.cs \
	cecil/Mono.Cecil/EventAttributes.cs \
	cecil/Mono.Cecil/AssemblyFlags.cs \
	cecil/Mono.Cecil/TypeDefinitionCollection.cs \
	cecil/Mono.Cecil/ModuleReference.cs \
	cecil/Mono.Cecil/EventDefinition.cs \
	cecil/Mono.Cecil/ParameterAttributes.cs \
	cecil/Mono.Cecil/MetadataSystem.cs \
	cecil/Mono.Cecil/TypeAttributes.cs \
	cecil/Mono.Cecil/GenericInstanceMethod.cs \
	cecil/Mono.Cecil/PointerType.cs \
	cecil/Mono.Cecil/MethodReturnType.cs \
	cecil/Mono.Cecil/ArrayType.cs \
	cecil/Mono.Cecil/PropertyDefinition.cs \
	cecil/Mono.Cecil/EmbeddedResource.cs \
	cecil/Mono.Cecil/FunctionPointerType.cs \
	cecil/Mono.Cecil/PinnedType.cs \
	cecil/Mono.Cecil/SentinelType.cs \
	cecil/Mono.Cecil/GenericInstanceType.cs \
	cecil/Mono.Cecil/AssemblyNameReference.cs \
	cecil/Mono.Cecil/ParameterReference.cs \
	cecil/Mono.Cecil/MethodDefinition.cs \
	cecil/Mono.Cecil/PInvokeInfo.cs \
	cecil/Mono.Cecil/IMethodSignature.cs \
	cecil/Mono.Cecil/AssemblyNameDefinition.cs \
	cecil/Mono.Cecil/VariantType.cs \
	cecil/Mono.Cecil/ExportedType.cs \
	cecil/Mono.Cecil/ManifestResourceAttributes.cs \
	cecil/Mono.Cecil/Resource.cs \
	cecil/Mono.Cecil/BaseAssemblyResolver.cs \
	cecil/Mono.Cecil/AssemblyInfo.cs \
	cecil/Mono.Cecil/ReferenceType.cs \
	cecil/Mono.Cecil/AssemblyLinkedResource.cs \
	cecil/Mono.Cecil/IMemberDefinition.cs \
	cecil/Mono.Cecil/TypeDefinition.cs \
	cecil/Mono.Cecil/AssemblyReader.cs \
	cecil/Mono.Cecil/ModuleDefinition.cs \
	cecil/Mono.Cecil/MemberDefinitionCollection.cs \
	cecil/Mono.Cecil/PropertyReference.cs \
	cecil/Mono.Cecil/FieldReference.cs \
	cecil/Mono.Cecil/TargetRuntime.cs \
	cecil/Mono.Cecil/IGenericInstance.cs \
	cecil/Mono.Cecil/PropertyAttributes.cs \
	cecil/Mono.Cecil/AssemblyHashAlgorithm.cs \
	cecil/Mono.Cecil/FileAttributes.cs \
	cecil/Mono.Cecil/GenericParameter.cs \
	cecil/Mono.Cecil/TypeReference.cs \
	cecil/Mono.Cecil/SecurityDeclaration.cs \
	cecil/Mono.Cecil/ParameterDefinition.cs \
	cecil/Mono.Cecil/GenericParameterAttributes.cs \
	cecil/Mono.Cecil/LinkedResource.cs \
	cecil/Mono.Cecil/AssemblyWriter.cs \
	cecil/Mono.Cecil/MethodSemanticsAttributes.cs \
	cecil/Mono.Cecil/EventReference.cs \
	cecil/Mono.Cecil/Import.cs \
	cecil/Mono.Cecil/MemberReference.cs \
	cecil/Mono.Cecil/FieldAttributes.cs \
	cecil/Mono.Cecil/IMarshalInfoProvider.cs \
	cecil/Mono.Cecil/ParameterDefinitionCollection.cs \
	cecil/Mono.Cecil/IGenericParameterProvider.cs
	
all: daisy.exe
	mono --debug bin/daisy.exe hello dy/hello.dy bin/hello.exe
	chmod u+x bin/hello.exe

daisy.exe: $(source)
	@gmcs -debug $(source) -out:bin/daisy.exe

bin/Parser.cs: src/daisy.atg
	coco/Coco.exe -namespace coco -frames coco -o bin src/daisy.atg

clean:
	rm -rf *~ bin/*

